//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiRisWeb.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://rishra.irad.cl/Multiriswebws/servicemultiris.asmx")]
        public string MultiRisWeb_WSSoranWeb_ServiceMultiris {
            get {
                return ((string)(this["MultiRisWeb_WSSoranWeb_ServiceMultiris"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hnaval.irad.cl/Multiriswebws/servicemultiris.asmx")]
        public string MultiRisWeb_WsHospNavTalcahuano_ServiceMultiris {
            get {
                return ((string)(this["MultiRisWeb_WsHospNavTalcahuano_ServiceMultiris"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://190.196.143.122/WSObtenertecnologo/ServiceSoran_Tecnologo.asmx")]
        public string MultiRisWeb_WS_Codelco_Tecnologo_ServiceSoran_Tecnologo {
            get {
                return ((string)(this["MultiRisWeb_WS_Codelco_Tecnologo_ServiceSoran_Tecnologo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ristalca.amis-rx.cl:1443/MultiriswebWS/ServiceMultiris.asmx")]
        public string MultiRisWeb_WSASTalca_ServiceMultiris {
            get {
                return ((string)(this["MultiRisWeb_WSASTalca_ServiceMultiris"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://riscloud.nuevaclinicacordillera.cl/MULTIRISWEBWS/ServiceMultiris.asmx")]
        public string MultiRisWeb_WsCordillera_ServiceMultiris {
            get {
                return ((string)(this["MultiRisWeb_WsCordillera_ServiceMultiris"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://riscloud.clinicaloscarrera.cl/multiriswebws/servicemultiris.asmx")]
        public string MultiRisWeb_WsLosCarrera_ServiceMultiris {
            get {
                return ((string)(this["MultiRisWeb_WsLosCarrera_ServiceMultiris"]));
            }
        }
    }
}
